import ItemMod from "src/models/ItemMod";
import { Aspect, ModRarity, ModType } from "src/models";
import { getAspect } from "./AspectList";

let ImportantStatsMods: Partial<ItemMod>[] = [
  {
    id: "I000",
    name: "NONE",
  },
  {
    id: "I001",
    name: "Dagger",
    DEX: 1,
    INT: 2,
    CriticalChance: 3,
    Clarity: 4,
  },
  {
    id: "I002",
    name: "Knuckles",
    VIT: 1,
    STR: 2,
    Armor: 3,
    PhysicalResist: 4,
  },
  {
    id: "I003",
    name: "Hatchet",
    STR: 1,
    CriticalDamage: 2,
    Attack: 3,
    PhysicalAmplification: 4,
  },
  {
    id: "I004",
    name: "Wakizashi",
    AGI: 1,
    STR: 2,
    Parry: 3,
    Deflect: 4,
  },
  {
    id: "I005",
    name: "Wand",
    INT: 1,
    LUK: 2,
    Arcana: 3,
    Clarity: 4,
  },
  {
    id: "I006",
    name: "",
  },
  {
    id: "I007",
    name: "Shortsword",
    STR: 1,
    DEX: 2,
    Attack: 3,
    Accuracy: 4,
  },
  {
    id: "I008",
    name: "Hooksword",
    STR: 1,
    WIL: 2,
    Attack: 3,
    Deflect: 4,
  },
  {
    id: "I009",
    name: "Scimitar",
    STR: 1,
    AGI: 2,
    Accuracy: 3,
    Finesse: 4,
  },
  {
    id: "I010",
    name: "Cutlass",
    AGI: 1,
    STR: 2,
    Deflect: 3,
    Attack: 4,
  },
  {
    id: "I011",
    name: "Rapier",
    DEX: 1,
    STR: 2,
    Finesse: 3,
    Parry: 4,
  },
  {
    id: "I012",
    name: "Sabre",
    STR: 1,
    DEX: 2,
    Parry: 3,
    Attack: 4,
  },
  {
    id: "I013",
    name: "Mace",
    STR: 1,
    VIT: 2,
    PhysicalAmplification: 3,
    Attack: 4,
  },
  {
    id: "I014",
    name: "Flail",
    VIT: 1,
    STR: 2,
    CriticalDamage: 3,
    CriticalChance: 4,
  },
  {
    id: "I015",
    name: "Club",
    FAI: 1,
    WIL: 2,
    Attack: 3,
    Truestrike: 4,
  },
  {
    id: "I016",
    name: "Hammer",
    STR: 1,
    FAI: 2,
    Attack: 3,
    CriticalDamage: 4,
  },
  {
    id: "I017",
    name: "Sceptre",
    CHA: 1,
    WIL: 2,
    Clarity: 3,
    Leadership: 4,
  },
  {
    id: "I018",
    name: "Orb",
    WIL: 1,
    INT: 2,
    Ward: 3,
    Clarity: 4,
  },
  {
    id: "I019",
    name: "Tome",
    INT: 1,
    WIL: 2,
    Arcana: 3,
    CriticalChance: 4,
  },
  {
    id: "I020",
    name: "",
  },
  {
    id: "I021",
    name: "Axe",
    STR: 1,
    CriticalDamage: 2,
    Attack: 3,
    PhysicalAmplification: 4,
  },
  {
    id: "I022",
    name: "Longsword",
    STR: 1,
    DEX: 2,
    Attack: 3,
    Accuracy: 4,
  },
  {
    id: "I023",
    name: "Katana",
    AGI: 1,
    STR: 2,
    Attack: 3,
    Finesse: 4,
  },
  {
    id: "I024",
    name: "Warhammer",
    STR: 1,
    FAI: 2,
    Attack: 3,
    CriticalDamage: 4,
  },
  {
    id: "I025",
    name: "Spear",
    AGI: 1,
    STR: 2,
    Truestrike: 3,
    Attack: 4,
  },
  {
    id: "I026",
    name: "Staff",
    INT: 1,
    WIL: 2,
    Arcana: 3,
    Clarity: 4,
  },
  {
    id: "I027",
    name: "",
  },
  {
    id: "I028",
    name: "Greatsword",
    STR: 1,
    DEX: 2,
    Attack: 3,
    CriticalDamage: 4,
  },
  {
    id: "I029",
    name: "Broadsword",
    STR: 1,
    DEX: 2,
    Attack: 3,
    Deflect: 4,
  },
  {
    id: "I030",
    name: "Greataxe",
    STR: 1,
    CriticalDamage: 2,
    Attack: 3,
    PhysicalAmplification: 4,
  },
  {
    id: "I031",
    name: "Greatstaff",
    INT: 1,
    STR: 2,
    Arcana: 3,
    Attack: 4,
  },
  {
    id: "I032",
    name: "Pike",
    STR: 1,
    AGI: 2,
    Attack: 3,
    Truestrike: 4,
  },
  {
    id: "I033",
    name: "Halberd",
    STR: 1,
    WIL: 2,
    Attack: 3,
    CriticalChance: 4,
  },
  {
    id: "I034",
    name: "Scythe",
    STR: 1,
    CHA: 2,
    Finesse: 3,
    Attack: 4,
  },
  {
    id: "I035",
    name: "Glaive",
    STR: 1,
    VIT: 2,
    Attack: 3,
    Finesse: 4,
  },
  {
    id: "I036",
    name: "",
  },
  {
    id: "I037",
    name: "Throwing Knife",
    DEX: 1,
    INT: 2,
    Finesse: 3,
    CriticalChance: 4,
  },
  {
    id: "I038",
    name: "Throwing Axe",
    STR: 1,
    CriticalDamage: 2,
    Attack: 3,
    PhysicalAmplification: 4,
  },
  {
    id: "I039",
    name: "Javelin",
    AGI: 1,
    STR: 2,
    Attack: 3,
    Truestrike: 4,
  },
  {
    id: "I040",
    name: "Stone",
    VIT: 1,
    STR: 2,
    Accuracy: 3,
    Attack: 4,
  },
  {
    id: "I041",
    name: "Chakram",
    STR: 1,
    DEX: 2,
    Attack: 3,
    Accuracy: 4,
  },
  {
    id: "I042",
    name: "Bomb",
    LUK: 1,
    FlameAmplification: 3,
  },
  {
    id: "I043",
    name: "",
  },
  {
    id: "I044",
    name: "Shortbow",
    AGI: 1,
    DEX: 2,
    Accuracy: 3,
    Clarity: 4,
  },
  {
    id: "I045",
    name: "Longbow",
    AGI: 1,
    DEX: 2,
    Accuracy: 3,
    Attack: 4,
  },
  {
    id: "I046",
    name: "Greatbow",
    AGI: 1,
    STR: 2,
    Attack: 3,
    CriticalDamage: 4,
  },
  {
    id: "I047",
    name: "Crossbow",
    AGI: 1,
    STR: 2,
    Attack: 3,
    CriticalDamage: 4,
  },
  {
    id: "I048",
    name: "",
  },
  {
    //resume
    id: "I049",
    name: "Hand Cannon",
    AGI: 1,

    Attack: 9,
    //piercing attack ALWAYS
    //chance to backfire
    //reload: locked out of evasion/deflect/parry/ward when fired
  },
  {
    id: "I050",
    name: "Blunderbus",
    Attack: 10,
    //piercing attack ALWAYS
    //choice to do melee or ranged (ranged has a harsh damage penalty)
    //reload: locked out of evasion/deflect/parry/ward when fired
  },
  {
    id: "I051",
    name: "",
  },
  {
    id: "I052",
    name: "Whip",
    Finesse: 8,
    //add finesse to normal attacks
  },
  {
    id: "I053",
    name: "Starsword",
    Attack: 5,
    Accuracy: 5,
    Deflect: 5,
    Parry: 5,
    Ward: 5,
  },
];

export function getImportantStatsMod(name: string): ItemMod {
  let result = ImportantStatsMods.find((element) => element.name === name);
  if (!result) result = ImportantStatsMods[0];
  if (result.modType == undefined) result.modType = "IMPORTANTSTATS";
  let merged: ItemMod = { ...new ItemMod(), ...result };
  return merged;
}
